### ISSUE TITLE
References pointing to wrong things!

### ISSUE THREAD

**Issue by plul** [StorjOld/whitepapers#8]
Description below is copy/paste from Slack: 

Another serious issue I discovered: There are two separate references to maidsafe in meta.bib. It looks very much like the second one, named 7, should be a reference to storj, not maidsafe. Which confuses me since reference named 6 actually is a reference to storj. Looking at it, it looks like some of the numbering got shifted by one at some point, because \cite{6} is meant to reference plowshare, but it actually references storj. While the reference named 5 in meta.bib is actually plowshare. I don't know what \cite{5} is actually supposed to point at, because \cite{1}-\cite{4} looks like they are correct.

I would like one of the authors to go through all the references and fix this.

**Comment by plul** [comment]
This traces back to commit 6f543dd when meta.bib was added btw.

**Comment by plul** [comment]
To clarify, this is in the metadisk paper.

**Comment by raraymon** [comment]
We ended up with two maidsafe references 

@misc{5,
title  = {Plowshare - Download and upload files from file sharing websites},
note   = {\url{https://code.google.com/p/plowshare/}},
year   = {(2014)}
}

@misc{6,
title  = {Storj - Decentralized Cloud Storage},
note   = {\url{ http://storj.io/}},
year   = {(2014)}
}

@misc{7,
title  = {Distributed Platform, MaidSafe},
note   = {\url{http://maidsafe.net}},
year   = {(2014)}
}

Should be changed to 

@misc{5,
title  = {What’s wrong with in-browser cryptography?},
note   = {\url{http://tonyarcieri.com/whats-wrong-with-webcrypto}},
year   = {(2013)}
}

@misc{6,
title  = {Plowshare - Download and upload files from file sharing websites},
note   = {\url{https://code.google.com/p/plowshare/}},
year   = {(2014)}
}

@misc{7,
title  = {Storj - Decentralized Cloud Storage},
note   = {\url{ http://storj.io/}},
year   = {(2014)}
}

**Comment by plul** [comment]
Updated in commit 277798.
